---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqm-gqe-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eqm-gqe-api
    spec:
      containers:
      - name: eqm-gqe-api
        image: tceqmgqe/eqm-gqe-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  selector:
    matchLabels:
      app: eqm-gqe-api
---
apiVersion: v1
kind: Service
metadata:
  name: eqm-gqe-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: eqm-gqe-api